version: "1.0"
info:
  model: int-scaffold
packages:
- name: Kvv_1205Project
  gitServerName: kvv
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
services:
- serviceName: project.kvv_1205.integrations:gv
  packages:
  - name: Kvv_1205Project
    version: "1.0"
- serviceName: pub.globalVariable:getGlobalVariable
  packages:
  - name: WmPublic
    version: 11.1.0.0.2055
